CREATE TABLE `fox_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `open_id` VARCHAR(64) NOT NULL COMMENT '微信小程序openid',
    `union_id` VARCHAR(64) DEFAULT NULL COMMENT '微信小程序unionid',
    `nickname` VARCHAR(50) DEFAULT NULL COMMENT '用户昵称',
    `avatar_url` VARCHAR(255) DEFAULT NULL COMMENT '用户头像URL',
    `gender` TINYINT DEFAULT 0 COMMENT '性别（0：未知，1：男，2：女）',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号码',
    `is_player` TINYINT DEFAULT 0 COMMENT '是否为俱乐部球员（0：否，1：是）',
    `player_number` VARCHAR(10) DEFAULT NULL COMMENT '球员号码（如果是球员）',
    `player_position` VARCHAR(20) DEFAULT NULL COMMENT '球员位置（如果是球员）',
    `status` TINYINT DEFAULT 1 COMMENT '用户状态（0：禁用，1：正常）',
    `competence` TINYINT DEFAULT 0 COMMENT '权限类型（0：访客用户，1：球员/俱乐部内部球员 2：使用用户(可参与正常功能)）',
    `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除（0：未删除，1：已删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_open_id` (`open_id`),
    KEY `idx_phone` (`phone`),
    KEY `idx_status` (`status`),
    KEY `idx_competence` (`competence`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='微信小程序用户表'; 