CREATE TABLE `fox_club_schedule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `club_id` bigint NOT NULL COMMENT '俱乐部ID',
  `game_type` tinyint NOT NULL COMMENT '赛制（1：五人制，2：六人制，3：七人制，4：八人制，5：十一人制）',
  `team_count` int NOT NULL COMMENT '参赛队伍数量',
  `total_players` int NOT NULL COMMENT '报名总人数',
  `registered_players` int NOT NULL DEFAULT '0' COMMENT '已报名人数',
  `waiting_players` int NOT NULL DEFAULT '0' COMMENT '排队人数',
  `address` varchar(255) NOT NULL COMMENT '比赛地址',
  `name` varchar(100) NOT NULL COMMENT '比赛名称',
  `start_time` datetime NOT NULL COMMENT '比赛开始时间',
  `end_time` datetime NOT NULL COMMENT '比赛结束时间',
  `creator_id` bigint NOT NULL COMMENT '发起人ID',
  `description` text COMMENT '比赛描述',
  `notice_id` bigint DEFAULT NULL COMMENT '比赛须知文案ID',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '比赛状态（0：未进行，1：进行中，2：已过期）',
  `venue` varchar(100) DEFAULT NULL COMMENT '比赛场地',
  `fee` int NOT NULL DEFAULT '0' COMMENT '比赛费用（单位：分）',
  `level` tinyint NOT NULL DEFAULT '1' COMMENT '比赛级别（1：养生，2：锻炼，3：激情）',
  `need_referee` tinyint NOT NULL DEFAULT '0' COMMENT '是否需要裁判（0：否，1：是）',
  `need_medical` tinyint NOT NULL DEFAULT '0' COMMENT '是否需要医疗人员（0：否，1：是）',
  `need_insurance` tinyint NOT NULL DEFAULT '0' COMMENT '是否需要保险（0：否，1：是）',
  `registration_deadline` datetime NOT NULL COMMENT '报名截止时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint NOT NULL DEFAULT '0' COMMENT '是否删除（0：否，1：是）',
  PRIMARY KEY (`id`),
  KEY `idx_club_id` (`club_id`),
  KEY `idx_creator_id` (`creator_id`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='俱乐部赛程表'; 