-- 创建俱乐部信息表
CREATE TABLE `fox_club` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` VARCHAR(100) NOT NULL COMMENT '俱乐部名称',
    `english_name` VARCHAR(200) DEFAULT NULL COMMENT '英文名称',
    `foundation_date` DATE NOT NULL COMMENT '成立时间',
    `total_players` INT DEFAULT 0 COMMENT '总球员数',
    `active_players` INT DEFAULT 0 COMMENT '活跃球员数',
    `total_matches` INT DEFAULT 0 COMMENT '已组织比赛数',
    `win_matches` INT DEFAULT 0 COMMENT '胜场数',
    `draw_matches` INT DEFAULT 0 COMMENT '平场数',
    `lose_matches` INT DEFAULT 0 COMMENT '负场数',
    `club_logo` VARCHAR(255) DEFAULT NULL COMMENT '俱乐部队徽URL',
    `club_background` VARCHAR(255) DEFAULT NULL COMMENT '俱乐部背景图URL',
    `club_motto` VARCHAR(200) DEFAULT NULL COMMENT '俱乐部格言',
    `current_coach` VARCHAR(50) DEFAULT NULL COMMENT '当前教练',
    `coach_phone` VARCHAR(20) DEFAULT NULL COMMENT '教练联系电话',
    `home_stadium` VARCHAR(100) DEFAULT NULL COMMENT '主场名称',
    `stadium_address` VARCHAR(200) DEFAULT NULL COMMENT '主场地址',
    `region` VARCHAR(50) DEFAULT NULL COMMENT '所在地区',
    `city` VARCHAR(50) DEFAULT NULL COMMENT '所在城市',
    `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '俱乐部联系电话',
    `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '俱乐部联系邮箱',
    `description` TEXT DEFAULT NULL COMMENT '俱乐部简介',
    `status` TINYINT DEFAULT 1 COMMENT '状态（0：未激活，1：正常，2：暂停运营）',
    `level` TINYINT DEFAULT 1 COMMENT '俱乐部等级',
    `experience` INT DEFAULT 0 COMMENT '俱乐部经验值',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除（0：未删除，1：已删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    KEY `idx_region_city` (`region`, `city`),
    KEY `idx_status` (`status`),
    KEY `idx_level` (`level`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='俱乐部信息表'; 