-- 创建球员主表
CREATE TABLE `fox_player` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `user_id` BIGINT NOT NULL COMMENT '关联用户ID',
    `name` VARCHAR(50) NOT NULL COMMENT '球员姓名',
    `english_name` VARCHAR(100) DEFAULT NULL COMMENT '英文名',
    `age` INT DEFAULT NULL COMMENT '年龄',
    `birth_date` DATE DEFAULT NULL COMMENT '出生日期',
    `height` INT DEFAULT NULL COMMENT '身高(cm)',
    `weight` INT DEFAULT NULL COMMENT '体重(kg)',
    `preferred_foot` TINYINT DEFAULT NULL COMMENT '惯用脚（1：左脚，2：右脚，3：双脚）',
    `position` VARCHAR(10) DEFAULT NULL COMMENT '场上位置（GK：门将，DF：后卫，MF：中场，FW：前锋）',
    `specific_position` VARCHAR(20) DEFAULT NULL COMMENT '具体擅长位置（如：中锋、边锋、后腰等）',
    `jersey_number` VARCHAR(10) DEFAULT NULL COMMENT '球衣号码',
    `club` VARCHAR(100) DEFAULT NULL COMMENT '效力俱乐部',
    `market_value` DECIMAL(12,2) DEFAULT NULL COMMENT '身价(欧元)',
    `region` VARCHAR(50) DEFAULT NULL COMMENT '地区',
    `city` VARCHAR(50) DEFAULT NULL COMMENT '城市',
    `local_fame` INT DEFAULT 0 COMMENT '当地名气（1-5）',
    `status` TINYINT DEFAULT 0 COMMENT '球员状态（0：未激活，1：正常，2：受伤，3：停赛,4：歇着,5: 已堕落）',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除（0：未删除，1：已删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_id` (`user_id`),
    KEY `idx_position` (`position`),
    KEY `idx_status` (`status`),
    KEY `idx_club` (`club`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='俱乐部球员表';

-- 创建球员能力值表
CREATE TABLE `fox_player_ability` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `player_id` BIGINT NOT NULL COMMENT '球员ID',
    `enchantment` VARCHAR(255) DEFAULT NULL COMMENT '附魔 (天赋)',
    `offensive_panel` VARCHAR(255) DEFAULT NULL COMMENT '进攻面板',
    `defensive_panel` VARCHAR(255) DEFAULT NULL COMMENT '防守面板',
    `overall_rating` INT DEFAULT NULL COMMENT '综合能力值（1-100）',
    `speed` INT DEFAULT NULL COMMENT '速度（1-100）',
    `strength` INT DEFAULT NULL COMMENT '力量（1-100）',
    `shooting` INT DEFAULT NULL COMMENT '射门（1-100）',
    `defending` INT DEFAULT NULL COMMENT '防守（1-100）',
    `dribbling` INT DEFAULT NULL COMMENT '盘带（1-100）',
    `passing` INT DEFAULT NULL COMMENT '传球（1-100）',
    `weak_foot` INT DEFAULT NULL COMMENT '逆足能力（1-100）',
    `skill_moves` INT DEFAULT NULL COMMENT '花式技巧（1-100）',
    `futsal_rating` INT DEFAULT NULL COMMENT '五人制能力（1-100）',
    `football_rating` INT DEFAULT NULL COMMENT '11人制能力（1-100）',
    `stamina` INT DEFAULT NULL COMMENT '体能（1-100）',
    `reactions` INT DEFAULT NULL COMMENT '反应（1-100）',
    `balance` INT DEFAULT NULL COMMENT '平衡（1-100）',
    `jumping` INT DEFAULT NULL COMMENT '弹跳（1-100）',
    `heading` INT DEFAULT NULL COMMENT '头球（1-100）',
    `saving` INT DEFAULT NULL COMMENT '门将特有属性：扑救（1-100）',
    `handling` INT DEFAULT NULL COMMENT '门将特有属性：手型（1-100）',
    `kicking` INT DEFAULT NULL COMMENT '门将特有属性：开球（1-100）',
    `positioning` INT DEFAULT NULL COMMENT '门将特有属性：站位（1-100）',
    `keeper_reactions` INT DEFAULT NULL COMMENT '门将反应（1-100）',
    `keeper_speed` INT DEFAULT NULL COMMENT '门将速度（1-100）',
    `update_time` DATETIME DEFAULT NULL COMMENT '能力值更新时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `is_deleted` TINYINT DEFAULT 0 COMMENT '是否删除（0：未删除，1：已删除）',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_player_id` (`player_id`),
    KEY `idx_overall_rating` (`overall_rating`),
    KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='球员能力值表'; 